
tasks:
 - name: aws-cli
   env:
     AWS_CLI_AUTO_PROMPT: on-partial
   init: |
    cd $THEIA_WORKSPACE_ROOT
    curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    unzip awscliv2.zip
    sudo ./aws/install
    rm -rf aws awcliv2.zip


vscode:
  extensions:
    - 42Crunch.vscode-openapi
